version: "3"

services:
  node:
    container_name: desafio-xp
    build: .
    image: node:16
    command: npm start
    restart: always
    working_dir: /app
    volumes: 
      - .:/app
    depends_on:
      - db
    ports:
      - 3001:$PORT
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      HOSTNAME: db

  db:
    container_name: desafio-xp-db
    image: mysql:5.7
    restart: always
    ports:
      - '3306:$DB_PORT'
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      TZ: America/Sao_Paulo
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
