version: "3"

services:
  node:
    container_name: desafio-xp
    build: .
    restart: always
    working_dir: /app
    volumes: 
      - .:/app
    depends_on:
      - db
    ports:
      - 3001:$PORT
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      HOSTNAME: db

  db:
    container_name: desafio-xp-db
    image: mysql:8.0
    restart: always
    ports:
      - '3306:$DB_PORT'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
